nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
codigo_seccion = input("Ingrese su Código-sección (ej. OMRA05): ")
sede = input("Ingrese su sede: ")

print("\n--- Información Ingresada ---")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("Código-sección:", codigo_seccion)
print("Sede:", sede)